name: Build GDrive CLI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
      id: go

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get https://github.com/zergolf1994/gdrive code
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        go get github.com/zergolf1994/gdrive

    - name: Change CLIENT ID & SECRET
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        cd $HOME/go/src/github.com/zergolf1994/gdrive/
        sed -i "s/376559405806-052kq1g218k3elkcuq5pv4k4so040ast.apps.googleusercontent.com/$CLIENT_ID/g" handlers_drive.go
        sed -i "s/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/$CLIENT_SECRET/g" handlers_drive.go

    - name: Build
      run: |
        cp -r build/* $HOME/go/src/github.com/zergolf1994/gdrive/
        cd $HOME/go/src/github.com/zergolf1994/gdrive/
